# Generated by Django 3.2.5 on 2021-09-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_doLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('to_do', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Todo list',
                'verbose_name_plural': 'Todo lists',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'User information',
                'verbose_name_plural': 'User information',
            },
        ),
    ]
